server:
  port: 8080

spring:
  profiles:
    active: local, local-secrets

  jpa:
    database-platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
